const UPDATE_GRID = "UPDATE_GRID";
const GET_EMPLOYEES_DETAIL_SUCCESS = "GET_EMPLOYEES_DETAIL_SUCCESS";
const GET_EMPLOYEES_DETAIL_FAILURE = "GET_EMPLOYEES_DETAIL_FAILURE";
const SET_PRIVIOUS_DATA = "SET_PRIVIOUS_DATA";

export {
  UPDATE_GRID,
  GET_EMPLOYEES_DETAIL_SUCCESS,
  GET_EMPLOYEES_DETAIL_FAILURE,
  SET_PRIVIOUS_DATA
};
